### PR TITLE
fix: fixed NPE exception in the WriteSheetWorkbookWriteHandler class

### LINKED ISSUE #564: [Bug] 使用fill功能时, 若第二个writeSheet没有赋值sheetNo, 报错空指针(仅1.3.0)
### Search before asking

- [x] I searched in the [issues](https://github.com/fast-excel/fastexcel/issues) and found nothing similar.

### Fastexcel version

1.3.0

### JDK version

1.8

### Operating system

win11

### Minimal reproduce step

此bug仅在1.3.0会触发, 其他版本没有这个问题

```java

        List<String> sheets = Arrays.asList("1", "2", "3");
        ExcelWriter excelWriter = null;
        try (ByteArrayOutputStream bos = new ByteArrayOutputStream();
             InputStream inputStream = this.getClass().getResourceAsStream("/template/spec_datasheet_template.xlsx");
             XSSFWorkbook workbook = new XSSFWorkbook(Objects.requireNonNull(inputStream))) {
            // 原模板只有一个sheet，通过poi复制出需要的sheet个数的模板
            // 设置模板sheet的名称
            workbook.setSheetName(1, SpecStrUtil.catalogSheetName(sheets.get(0)));
            for (int i = 1; i < sheets.size(); i++) {
                // 复制模板
                workbook.cloneSheet(1, SpecStrUtil.catalogSheetName(sheets.get(i)));
            }
            // 写到流里, Excel以它为模板
            workbook.write(bos);
            byte[] bArray = bos.toByteArray();
            InputStream is = new ByteArrayInputStream(bArray);
            excelWriter = FastExcel.write(response.getOutputStream())
                    .withTemplate(is)
                    .inMemory(true)
                    .build();
            WriteSheet catalogWriteSheet = FastExcel.writerSheet(0, "Menu").build();
            excelWriter.write(Collections.emptyList(), catalogWriteSheet);

            FillConfig fillConfig = FillConfig.builder().forceNewRow(Boolean.TRUE).build();
            // 数据sheet
            int sheetNo = 1;
            for (String sheetName : sheets) {
                // 需要根据name来填充相应的数据
                WriteSheet writeSheet = FastExcel.writerSheet(SpecStrUtil.catalogSheetName(sheetName))
//                        .sheetNo(sheetNo++)
                        .build();
                // 填充目录信息
                excelWriter.fill(sheetName, writeSheet);
            }
        } catch (Exception e) {
            log.error("文件异常", e);
            throw new GuwaveException("文件异常", e);
        } finally {
            // 关闭流
            if (excelWriter != null) {
                excelWriter.close();
            }
        }
```

上面是简单的复现代码, 其中注释的代码是引发bug的地方, 在1.3.0之前是不需要设置sheetNo的, 期望应该是根据sheetName填充对应的数据. 但是这里需要加上sheetNo来避免报错

另外在业务代码中这个列表并非是有序的, 所以这里是只赋值sheetName来自动识别填充. 现在就需要额外的逻辑保证有序. 

具体在fastExcel中的话是在下图, 其中keySet中存在null值, sorted报错

Image

在这里赋值, 其中sheetNo在上面的业务代码中没有赋值, 所以为null, 导致之后的sorted报错

Image

不知道这是不是本意...但之前的版本是ok的, 所以我觉得应该是个bug

### What did you expect to see?

不报错, 并且直觉上应该是根据sheetName来填充吧

### What did you see instead?

无

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by delei**
## Purpose of the pull request

Close #564 

## What's changed?

- fix the NPE exception in the stream
- ensure sheetNo is set for writeSheetHolder

## Checklist

- [x] I have read the [Contributor Guide](https://fast-excel.github.io/fastexcel/community/contribution).
- [x] I have written the necessary doc or comment.
- [x] I have added the necessary unit tests and all cases have passed.

### CODE REVIEW

File: fastexcel/src/test/java/cn/idev/excel/writesheet/WriteSheetTest.java [hunk 1]
```diff
@@ -81,6 +86,49 @@ private Map<Integer, Integer> initSheetDataSizeList(List<Integer> sheetNoList) {
...
+            // sheetName is empty
+            int sheetNo = 0;
+            WriteSheet writeSheet = FastExcel.writerSheet(sheetNo).build();
+            excelWriter.write(dataList(dataMap.get(sheetNo)), writeSheet);
+            Assertions.assertEquals(
+                    sheetNo, excelWriter.writeContext().writeSheetHolder().getSheetNo());
+
+            // sheetNo is empty
+            sheetNo = 1;
+            writeSheet = FastExcel.writerSheet(sheetNameList.get(sheetNo)).build();
```
Comment (alaahong) [inline fastexcel/src/test/java/cn/idev/excel/writesheet/WriteSheetTest.java:109]: As copilot mentioned, seems write No as Name here?

Comment (delei) [reply fastexcel/src/test/java/cn/idev/excel/writesheet/WriteSheetTest.java:109]: `sheetNameList.get(sheetNo)`

The value set is the sheet name obtained from sheetNameList.
